<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5a04aa94d7fc4',
		'title' => 'Date',
		'fields' => array(
			array(
				'key' => 'field_5a04aaadf505a',
				'label' => 'Start',
				'name' => 'start',
				'type' => 'date_time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'hidden',
					'id' => '',
				),
				'display_format' => 'd/m/Y g:i a',
				'return_format' => 'Y-m-d H:i:s',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5a04aabc9bdb4',
				'label' => 'End',
				'name' => 'end',
				'type' => 'date_time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'hidden',
					'id' => '',
				),
				'display_format' => 'd/m/Y g:i a',
				'return_format' => 'Y-m-d H:i:s',
				'first_day' => 1,
			),
			array(
				'key' => 'field_59d3b5fd686af',
				'label' => 'Start date',
				'name' => 'start_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => 'start_date',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'Y-m-d',
				'first_day' => 1,
			),
			array(
				'key' => 'field_59f49bd5b0e1b',
				'label' => 'Start time',
				'name' => 'start_time',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '21',
					'class' => '',
					'id' => 'start_time',
				),
				'display_format' => 'H:i',
				'return_format' => 'H:i:s',
			),
			array(
				'key' => 'field_59d3b616686b0',
				'label' => 'End Date',
				'name' => 'end_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => 'end_date',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'Y-m-d',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5a0175376b139',
				'label' => 'End time',
				'name' => 'end_time',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '21',
					'class' => '',
					'id' => 'end_time',
				),
				'display_format' => 'H:i',
				'return_format' => 'H:i:s',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gc_event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
	));

endif;